name: Build Electron App
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # Aquí es donde GitHub usa una computadora con Linux
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Code
        run: |
          npx vite build
          npx vite build --outDir dist-electron --main
          ls -R dist-electron  # Esto nos dirá en la consola si el archivo existe

      - name: Package App for Linux
        run: npx electron-builder --linux AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}